config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #verb path controller#action
  get "pets", to: "pets#index"
  get "pets/new", to: "pets#new", as: :new_pet
  post "pets", to: "pets#create"
  get "pets/:id", to: "pets#show", as: :pet
  get "pets/:id/edit", to: "pets#edit", as: :edit
  patch "pets/:id", to: "pets#update"
  delete "pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat parrot turtle lion)
  validates :name, presence: true
  validates :species, inclusion: {in: SPECIES}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container my-5">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: pet do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :species %>
    <%= f.select :species, collection: Pet::SPECIES, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :found_on %>
    <%= f.date_field :found_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<div class="container mt-5">
  <h1>Edit <%= @pet.name %></h1>

  <%= render "form", pet: @pet %>
</div>

app/views/pets/index.html.erb
<div class="container mt-5">
  <h1>PETS</h1>

  <ul>
    <% @pets.each do |pet| %>
      <li><%= link_to pet.name, pet_path(pet) %></li>
    <% end %>
  </ul>

  <%= link_to "Add a pet", new_pet_path %>
</div>

app/views/pets/new.html.erb
<div class="container mt-5">
  <h1>Add a new pet</h1>

  <%= render "form", pet: @pet %>
</div>

app/views/pets/show.html.erb
<div class="container mt-5">
  <h1><%= @pet.name %> <small>(<%= @pet.species %>)</small></h1>
  <ul>
    <li>Address: <%= @pet.address %></li>
    <li>Found on: <%= @pet.found_on %></li>
  </ul>

  <%= link_to "Edit #{@pet.name}", edit_path(@pet) %>
  <br>
  <%= link_to "Delete #{@pet.name}", pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" } %>
  <br>
  <%= link_to "Back to all pets", pets_path %>
</div>